module.exports = {
    "dishes":[
        "Gindara saikyo-yaki",
        "Horsemeat",
        "Warabi mochi",
        "Umi-budo",
        "sushi",
        "Chirashi-don",
        "Tonkatsu",
        "Wagyu",
        "Tempura",
        "Ramen",
        "Satsuma-age",
        "Te-uchi soba",
        "Sanuki udon",
        "Japanese curry rice",
        "Yaki-imo",
        "Taimeshi",
        "Takoyaki",
        "Kabayaki",
        "Ochazuke",
        "Onigiri",
        "Tofu",
        "Natto",
        "Okonomiyaki/monjayaki",
        "Nabe",
        "miso",
        "mochi",
        "Namero",
        "Gyoza",
        "Taco rice",
        "Naporitan spaghetti",
        "Yakitori",
        "Oden",
        "Rare cheesecake",
        "Dojo (loach)",
        "Tamago-yaki/dashimaki tamago",
        "Taiyaki",
        "Sekihan",
        "Tsukemono",
        "Karaage",
        "Matcha Latte"
        ]
};